version: '3'
services:
    weblogic:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 7001:7001
            - 7003:7003
            - 9002:9002
        environment:
            - ADMINISTRATION_PORT_ENABLED=false
            - DOMAIN_NAME=base_domain
            - SERVER_NAME1=APP01
        volumes:
            - /home/docker/weblogic-src/properties/:/u01/oracle/properties
            - /home/docker/weblogic-src/weblogic-external:/var/weblogic-external
            - /home/docker/weblogic-src/weblogic-external-data:/var/weblogic-external-data
        entrypoint: ["/u01/oracle/wait-for-it.sh","oradb:5500","--timeout=0","--strict", "--", "/u01/oracle/createAndStartEmptyDomain.sh" ]
        depends_on:
            - oradb
        networks:
            - mynet            
    oradb:
        build:
            context: ./
            dockerfile: Dockerfile-oradb
        environment:
            - ORACLE_SID=ORCLCDB
            - ORACLE_PDB=ORCLPDB
            - ORACLE_PWD=oracle
            - ORACLE_CHARACTERSET=we8mswin1252        
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - /home/docker/weblogic-src/dmp/:/dmp
        networks:
            - mynet
networks:
    mynet:
        ipam:
            driver: default
            config:
                - subnet: 172.21.238.0/24



